plugin_outlet:
  default: "above-right-sidebar-blocks"
hide_on_mobile:
  default: false
topic_id: 2005
pin_img: 'https://demo-connect.efinancethai.com/uploads/default/original/2X/1/15b3fd28bc7ccd31e201ad3c807038b3b81f5850.png'
title: 'ปักหมุด'
url_must_contain:
  type: list
  list_type: simple
  default: /latest|/categories|/new|/unread|/top*|/tag/*|/tags/*|/c/*|/t/*